format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$env_var\
$character"""

[directory]
style = "245"  # Medium gray

[character]
success_symbol = "[❯](243)"  # Dark gray
error_symbol = "[❯](167)"  # Muted red/brown
vimcmd_symbol = "[❮](71)"  # Dark green

[git_branch]
format = "[$branch]($style)"
style = "71"  # Dark green

[git_status]
format = "[[(*$conflicted$modified$staged)](240) ($ahead_behind)]($style)"
style = "243"  # Dark gray
# Optimized for worktree repos - only show essential status
conflicted = "​"
modified = "​"
staged = "​"
# Disable expensive checks that cause lock contention
renamed = ""
deleted = ""
stashed = ""
untracked = ""
# Fail fast to avoid lock conflicts in worktree repos
ignore_submodules = true
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "243"  # Dark gray

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[env_var.CLAUDE_AGENT_MODE]
format = "[$env_value]($style) "
style = "bold 243"
disabled = false

