#!/bin/sh

if [ "$(tmux display-message -p -F "#{session_name}")" = "popup" ];then
    tmux detach-client
else
    tmux popup \
      -w80% -h80% \
      -E "tmux attach -t popup || tmux new -s popup"
fi
