---
- hosts: localhost
  connection: local
  vars:
    packages:
      - autopep8
      - dbx
      - jupyterlab
      - jupytext
      - ruff
      - pyright
      - python-lsp-server[all]
      - thefuck
      - visidata
      - shell-gpt
      - tiktoken
      - prompt-toolkit
      - pynvim
      - requests
      - python-dotenv
  tasks:
    - name: Installing python packages
      loop: "{{ packages }}"
      ansible.builtin.shell: "pip install {{ item }}"
