---
- hosts: localhost
  connection: local
  vars:
    packages:
      - visidata
      - thefuck
  tasks:
    - name: Installing python packages
      loop: "{{ packages }}"
      ansible.builtin.shell: "pip install {{ item }}"

