---
- hosts: localhost
  connection: local
  vars:
    packages:
      - autopep8
      - dbx
      - jupyterlab
      - jupytext
      - pyright
      - python-lsp-server[all]
      - thefuck
      - visidata
  tasks:
    - name: Installing python packages
      loop: "{{ packages }}"
      ansible.builtin.shell: "pip install {{ item }}"

